kind = "mobile"
previewPath = "/"
title = "HOLA! User App"
version = "1.0.0"
id = "artifacts/mobile-user"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23106

[services.development]
run = "pnpm --filter @workspace/mobile-user run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile-user", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mobile-user", "run", "serve" ]

[services.env]
PORT = "23106"
BASE_PATH = "/"
